[
  { graph: "1" },
  { thing: "2" },
  { root: "3" },
  {
    rootEdge: "4",
    script: "5",
    ui: "6",
    events: "7",
    test2: null,
    test3: true,
    test4: 1,
    test5: "8",
    array: "9",
    pointer: "10",
    css: "11"
  },
  "root",
  ,
  { root: "12" },
  { keyed: "13", ordered: "14" },
  "some string",
  [1, "15", "16", true, "17"],
  { test: "18" },
  { "@global": "19" },
  {
    render: true,
    rootEdge: "20",
    script: "21",
    events: "22",
    test1: "23",
    test2: "24",
    test3: "25",
    test4: "26",
    test5: "27",
    array: "28",
    pointer: "29",
    css: "30"
  },
  {},
  [],
  "string",
  { object: true },
  [1, 2, 3],
  "cool",
  {
    "[contenteditable]": "31",
    ".value-container": "32",
    ".value": "33",
    ".add-edge": "34",
    ".edge-info-container": "35",
    ".edge-options": "36",
    ".edge-info": "37"
  },
  { render: false },
  { render: false, seenValues: "38" },
  { render: false },
  { render: false },
  { render: false },
  { render: false },
  { render: false },
  { render: false },
  { render: false },
  { render: false },
  { render: false },
  { "&:focus": "39" },
  { marginLeft: "40", width: "41" },
  {},
  { transition: "42", "&:hover": "43", "&:hover, &:focus": "44" },
  { display: "45", "&:hover ": "46", "&.pill-form": "47" },
  {
    padding: "48",
    width: "49",
    display: "50",
    transition: "51",
    opacity: 0,
    "&:hover ": "52"
  },
  { display: "45" },
  { render: false },
  { outline: "53" },
  "10px",
  "auto",
  "all 500mss ease",
  { cursor: "54" },
  {},
  "inline-block",
  { "&.edge-options": "55" },
  {
    color: "56",
    backgroundColor: "57",
    borderRadius: "58",
    padding: "59",
    transition: "60",
    marginTop: "61",
    ".edge-info": "62"
  },
  "0px !important",
  "0px",
  "none",
  "all 350ms, ease",
  { cursor: "54" },
  "0px solid transparent",
  "pointer",
  { padding: "63", width: "64", opacity: 1 },
  "white",
  "#42b983",
  "8px",
  "0px 2px",
  "all 350ms ease",
  "6px",
  { padding: "65" },
  "2px 2px !important",
  "initial",
  "2px 2px"
];


let root = { 
	types: { 
		types: "object", 
		"types.types": "string", 
		"types[\"types.types\"]": "string", 
		"types[\"types[\"types.types\"]\"]": "string", 
		"etc.." : "etc.."
	}
}